version: '3.7'

services:
  client:
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Dockerfile
    image: jlcomp03/todo-app-client
    container_name: container_client
    command: npm start
    volumes:
      - ./client/src/:/usr/app/src
      - ./client/public:/usr/app/public
      # - /usr/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - frontend
    stdin_open: true
    tty: true
  server:
    depends_on:
      - mongo
    build:
      context: ./server
      dockerfile: Dockerfile
    image: jlcomp03/todo-app-server
    container_name: container_server
    # command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./server/src:/usr/app/src
      # - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    links:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGODB_CONNSTRING='mongodb://container_mongodb:27017/todo_db'
    networks:
      - frontend
      - backend
  mongo:
    image: mongo
    restart: always
    container_name: container_mongodb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

volumes:
  mongo-data:
    driver: local
  node_modules:
  web-root:
    driver: local
    
networks:
  backend:
    driver: bridge
  frontend:

